### ISSUE TITLE
Lock helm version missing

### ISSUE THREAD

**Issue by wcarlsen** [dfds/k8s-monitoring#1]
Helm with Hellman cluster only works with version 2.12.* I think, and as of writing this Helm is on 2.14.*.

**Comment by HenrikStanley** [comment]
helm init --upgrade


➜ helm version       
'Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
