### ISSUE TITLE
deploy-grafana.sh is not idempotent

### ISSUE THREAD

**Issue by martimors** [dfds/k8s-monitoring#11]
If for whatever reason something goes wrong when running the `deploy-grafana.sh` script (network error for example), the script cannot be re-run because of the `kubectl create secret` command. By changing this part to `apply` somehow, the script could be a bit more flexible.

**Comment by wcarlsen** [comment]
You could easily achieve this by writing:

```bash
kubectl --namespace $NAMESPACE create secret generic "$secret" --from-literal=admin-user=admin --from-literal=admin-password="$ADMIN_PASSWORD" --dry-run=client -o yaml | kubectl apply -f -
```
