### ISSUE TITLE
Alerts to MS Teams

### ISSUE THREAD

**Issue by felipepoulsen** [dfds/k8s-monitoring#15]
Is it possible to add that we can send alerts to teams?

EDIT by @avnes:

This is a feature request about being able to send Grafana alerts to a webhook to MS Teams in Grafana instances belonging to the teams (not the CE Grafana instance).

**Comment by avnes** [comment]
@felipepoulsen Do you mean MS Teams? Or do you mean the members of a capability? (The latter should already be setup)

**Comment by avnes** [comment]
Blocked until @felipepoulsen gets back with more info.

**Comment by felipepoulsen** [comment]
I mean MS Teams. Would be convenient if I could pass a webhook url to a teams channel

**Comment by avnes** [comment]
Thanks for your input. I will now place this ticket in Refinement, so our product owner can have a look at it, and prioritize it if he wants this feature added.
