### ISSUE TITLE
Slack webhook exposed in configmap

### ISSUE THREAD

**Issue by runeabrahamsson** [dfds/k8s-monitoring#2]
In the created configmap for grafana the slack webhook is exposed.
It is mounted as a file which should be convertible to a secret resource instead.

**Comment by wcarlsen** [comment]
An issue created in the Grafana helm chart https://github.com/helm/charts/issues/16308#issuecomment-534876860

**Comment by wcarlsen** [comment]
Issue is stale and will be closed
