### ISSUE TITLE
Will this setup be broken when we move to traefik v2?

### ISSUE THREAD

**Issue by martimors** [dfds/k8s-monitoring#6]
I think this helm chart deploys a k8s vanilla ingress, not ingressroute. Could be that we have to deploy the ingressroute on the side and disable the ingress from the chart.

**Comment by abstrask** [comment]
Thanks for highlighting. We will address this as soon as possible.

**Comment by avnes** [comment]
@dingobar - Thanks for highlighting this. I have now merged a fix that creates a Traefik v2 ingressroute and middleware instead.
